#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#by considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# X(n) = X(n-1) + X(n-2)



sum = 0

  first = 1
 	second = 2
	 	
  while second < 4000000
  	#add to sum only if second is even
    sum += second if second.even?
    #first is equal to to second, and second is equal to first + second
  	first, second = second, first + second 	
 	end
 puts sum
  



